version: "3"
services:
  web:
    container_name: rakugaki_backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb:5000/
      - AWS_ACCESS_KEY_ID=aaa
      - AWS_SECRET_ACCESS_KEY=aaa
      - AWS_SESSION_TOKEN=aaa
    volumes:
      - .:/go/src/app
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    container_name: rakugaki_db
    build:
      context: .
      dockerfile: Dockerfile_dynamo
    user: root
    command: -jar DynamoDBLocal.jar -dbPath /var/lib/dynamo/data
    volumes:
      - ./tmp/db:/var/lib/dynamo/data
    ports:
      - 5000:5000
