version: "3"
services:
  web:
    container_name: rakugaki_backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DYNAMO_ENDPOINT=http://rakugaki_db:8000
      - AWS_ACCESS_KEY_ID=aaa
      - AWS_SECRET_ACCESS_KEY=aaa
      - AWS_SESSION_TOKEN=aaa
    volumes:
      - .:/go/src/app
    ports:
      - 8080:8080
    networks:
      - network

  db:
    container_name: rakugaki_db
    image: amazon/dynamodb-local:latest
    user: root
    command: -jar DynamoDBLocal.jar sharedDb -dbPath /var/lib/dynamo/data -optimizeDbBeforeStartup
    volumes:
      - ./tmp/db:/var/lib/dynamo/data
    ports:
      - 8000:8000
    networks:
      - network

  db-admin:
    container_name: rakugaki_admin
    image: aaronshaf/dynamodb-admin:latest
    environment:
      - DYNAMO_ENDPOINT=rakugaki_db:8000
    ports:
      - 8001:8001
    depends_on:
      - db
    networks:
      - network

networks:
  network:
    driver: bridge
